-- MySQL Script generated by MySQL Workbench
-- Sat May 16 18:32:59 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema carpoolplanner
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema carpoolplanner
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `carpoolplanner` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `carpoolplanner` ;

-- -----------------------------------------------------
-- Table `carpoolplanner`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carpoolplanner`.`role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ext_id` TINYINT UNSIGNED NULL,
  `name` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `ext_id_UNIQUE` (`ext_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carpoolplanner`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carpoolplanner`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(32) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `forgot_password` VARCHAR(256) NULL,
  `avatar` VARCHAR(256) NULL,
  `role` TINYINT UNSIGNED NOT NULL,
  `discord_token` VARCHAR(64) NULL,
  `discord_avatar` VARCHAR(256) NULL,
  `notify_email` BIT(1) NOT NULL,
  `notify_discord` BIT(1) NOT NULL,
  `last_login` DATETIME NOT NULL,
  `registered` DATETIME NOT NULL,
  `activated` BIT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `role_idx` (`role` ASC),
  CONSTRAINT `user_role`
    FOREIGN KEY (`role`)
    REFERENCES `carpoolplanner`.`role` (`ext_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carpoolplanner`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carpoolplanner`.`status` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ext_id` TINYINT UNSIGNED NULL,
  `name` VARCHAR(32) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `ext_id_UNIQUE` (`ext_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carpoolplanner`.`proposal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carpoolplanner`.`proposal` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `start_city` VARCHAR(64) NOT NULL,
  `start_lat` FLOAT NOT NULL,
  `start_lng` FLOAT NOT NULL,
  `start_date` DATETIME NOT NULL,
  `polyline` LONGTEXT NULL,
  `available_seats` TINYINT UNSIGNED NOT NULL,
  `max_seats` TINYINT UNSIGNED NOT NULL,
  `return` BIT(1) NOT NULL,
  `return_city` VARCHAR(64) NULL,
  `return_lat` FLOAT NULL,
  `return_lng` FLOAT NULL,
  `return_date` DATETIME NULL,
  `return_polyline` LONGTEXT NULL,
  `return_available_seats` TINYINT UNSIGNED NULL,
  `return_max_seats` TINYINT UNSIGNED NULL,
  `detour_radius` TINYINT UNSIGNED NOT NULL,
  `description` TEXT(500) NOT NULL,
  `smoking_allowed` BIT(1) NOT NULL,
  `free` BIT(1) NOT NULL,
  `created` DATETIME NOT NULL,
  `last_edited` DATETIME NOT NULL,
  `status` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `status_idx` (`status` ASC),
  CONSTRAINT `proposal_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `carpoolplanner`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `proposal_status`
    FOREIGN KEY (`status`)
    REFERENCES `carpoolplanner`.`status` (`ext_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carpoolplanner`.`passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carpoolplanner`.`passenger` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `proposal_id` INT UNSIGNED NOT NULL,
  `start_city` VARCHAR(64) NOT NULL,
  `start_lat` FLOAT NOT NULL,
  `start_lng` FLOAT NOT NULL,
  `needed_seats` TINYINT UNSIGNED NOT NULL,
  `return` BIT(1) NOT NULL,
  `return_city` VARCHAR(64) NULL,
  `return_lat` FLOAT NULL,
  `return_lng` FLOAT NULL,
  `asked` DATETIME NOT NULL,
  `message` TEXT(500) NOT NULL,
  `joined` DATETIME NOT NULL,
  `left` DATETIME NOT NULL,
  `status` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `proposal_id_idx` (`proposal_id` ASC),
  INDEX `status_idx` (`status` ASC),
  CONSTRAINT `passenger_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `carpoolplanner`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `passenger_proposal_id`
    FOREIGN KEY (`proposal_id`)
    REFERENCES `carpoolplanner`.`proposal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `passenger_status`
    FOREIGN KEY (`status`)
    REFERENCES `carpoolplanner`.`status` (`ext_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carpoolplanner`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carpoolplanner`.`request` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `start_city` VARCHAR(64) NOT NULL,
  `start_lat` FLOAT NOT NULL,
  `start_lng` FLOAT NOT NULL,
  `start_date` DATETIME NOT NULL,
  `needed_seats` TINYINT UNSIGNED NOT NULL,
  `return` BIT(1) NOT NULL,
  `return_city` VARCHAR(64) NULL,
  `return_lat` FLOAT NULL,
  `return_lng` FLOAT NULL,
  `return_date` DATETIME NULL,
  `description` TEXT(500) NOT NULL,
  `smoker` BIT(1) NOT NULL,
  `created` DATETIME NOT NULL,
  `last_edited` DATETIME NOT NULL,
  `status` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `status_idx` (`status` ASC),
  CONSTRAINT `request_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `carpoolplanner`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `request_status`
    FOREIGN KEY (`status`)
    REFERENCES `carpoolplanner`.`status` (`ext_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carpoolplanner`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carpoolplanner`.`permission` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ext_id` TINYINT UNSIGNED NULL,
  `name` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `ext_id_UNIQUE` (`ext_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carpoolplanner`.`role_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carpoolplanner`.`role_permission` (
  `role_id` TINYINT UNSIGNED NOT NULL,
  `permission_id` TINYINT UNSIGNED NOT NULL,
  INDEX `role_id_idx` (`role_id` ASC),
  INDEX `permission_id_idx` (`permission_id` ASC),
  CONSTRAINT `role_permission_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `carpoolplanner`.`role` (`ext_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role_permission_permission_id`
    FOREIGN KEY (`permission_id`)
    REFERENCES `carpoolplanner`.`permission` (`ext_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carpoolplanner`.`notification_link_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carpoolplanner`.`notification_link_category` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  `url` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carpoolplanner`.`notification_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carpoolplanner`.`notification_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ext_id` TINYINT UNSIGNED NULL,
  `name` VARCHAR(32) NOT NULL,
  `link_category` TINYINT UNSIGNED NULL,
  `default_text` VARCHAR(255) NOT NULL,
  `color` VARCHAR(6) NULL,
  `board_displayed` BIT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `ext_id_UNIQUE` (`ext_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `link_category_idx` (`link_category` ASC),
  CONSTRAINT `notification_type_link_category`
    FOREIGN KEY (`link_category`)
    REFERENCES `carpoolplanner`.`notification_link_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carpoolplanner`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carpoolplanner`.`notification` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `text` VARCHAR(255) NULL,
  `user_id_second` INT UNSIGNED NULL,
  `link_id` INT UNSIGNED NULL,
  `email_notified` VARCHAR(128) NULL,
  `discord_notified` VARCHAR(32) NULL,
  `type` TINYINT UNSIGNED NOT NULL,
  `read` BIT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `user_id_second_idx` (`user_id_second` ASC),
  INDEX `link_id_idx` (`link_id` ASC),
  INDEX `type_idx` (`type` ASC),
  CONSTRAINT `notification_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `carpoolplanner`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `notification_user_id_second`
    FOREIGN KEY (`user_id_second`)
    REFERENCES `carpoolplanner`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `notification_link_id`
    FOREIGN KEY (`link_id`)
    REFERENCES `carpoolplanner`.`proposal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `notification_link_id2`
    FOREIGN KEY (`link_id`)
    REFERENCES `carpoolplanner`.`request` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `notification_type`
    FOREIGN KEY (`type`)
    REFERENCES `carpoolplanner`.`notification_type` (`ext_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
